name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: riscv64:ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        rm -rf build/ || true
        mkdir build && cp ./check_predict.sh build/check_predict.sh && cp ./check_tomasulo.sh build/check_tomasulo.sh
        cd build && cmake -DJUDGE_ONLINE:STRING=true ..
        make

    - name: Run tests
      run: |
        bash check_tomasulo.sh
        bash check_predict.sh

    - name: Cleanup
      run: |
        cd ~/ && rm -rf build
